name: build-and-test-nest-starter-project

on:
  pull_request:
    branches: ['main']

jobs:
  lint-build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: enable corepack and set yarn version to latest stable
        run: |
          corepack enable

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint - Format check
        run: yarn run lint

      - name: Build project
        run: yarn run build

      - name: Run tests
        run: yarn run test:e2e
