name: pm2-devops-deploy

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag (e.g., v1.0.0) to deploy'
        required: true
        type: string
        default: 'vx.x.x'
      environment:
        description: 'Environment to use while deploying'
        required: true
        default: 'ec2_prod_server'
        type: choice
        options:
          - ec2_prod_server
          - pm2_prod
          - uat
      version_to_rollback:
        description: 'Version to rollback to (leave empty for new deployment)'
        required: false
        type: string
        default: ''

env:
  PROJECT_PATH: ${{ vars.PROJECT_DIR }}/${{ github.event.repository.name }}

jobs:
  pre-jobs-compute:
    environment: ${{ github.event.inputs.environment }}
    runs-on: [DEVOPS-UBU-DEV]
    outputs:
      NODE_VERSION: ${{ steps.node-version.outputs.NODE_VERSION }}
    steps:
      - name: Compute outputs
        id: node-version
        run: |
          echo "NODE_VERSION=${{ vars.NODE_VERSION }}" >> $GITHUB_OUTPUT

  create-release:
    if: inputs.version_to_rollback == '' # Only create release for new deployments
    environment: ${{ github.event.inputs.environment }}
    runs-on: ${{matrix.runner}}
    strategy:
      matrix:
        runner: [DEVOPS-UBU-DEV]
    permissions:
      contents: write # Needed for creating releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          target_commitish: ${{ github.ref_name }}
          tag_name: ${{ inputs.tag_name }}
          name: Release ${{ inputs.tag_name }}
          generate_release_notes: true

  build-and-deploy:
    needs: [create-release, pre-jobs-compute]
    runs-on: ${{matrix.runner}}
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.pre-jobs-compute.outputs.NODE_VERSION) }}
        runner: [DEVOPS-UBU-DEV]
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Print NODE_VERSION
        run: echo "Node version is ${{ fromJson(needs.pre-jobs-compute.outputs.NODE_VERSION)}}"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout tag
        run: git checkout ${{ github.event.inputs.tag_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build application
        run: yarn run build

      - name: Cache production dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-prod-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-prod-

      - name: Deploy with PM2
        run: |
          # Create project directory if it doesn't exist
          mkdir -p ${{ env.PROJECT_PATH }}/dist

          # Copy build files to project directory
          cp -r dist/* ${{ env.PROJECT_PATH }}/dist/
          cp package*.json yarn.lock .yarnrc.yml ${{ env.PROJECT_PATH }}

          # Install production dependencies
          cd ${{ env.PROJECT_PATH }}
          yarn install --immutable

          # Restart or Reload the app, Check if it's running in fork mode, if yes restart in cluster mode

          APP_NAME=${{ github.event.repository.name }}
          INSTANCES=$(pm2 jlist | jq --arg app_name "$APP_NAME" '.[] | select(.name == $app_name) | .pm2_env.instances // 0' | head -n 1)

          if [[ "$INSTANCES" -gt 4 ]]; then
            echo "PM2 app $APP_NAME is running with $INSTANCES instances."
            pm2 reload $APP_NAME --update-env
          else
            echo "PM2 app $APP_NAME is running less than 4 instances ($INSTANCES)."
            pm2 delete $APP_NAME || true
            if [ -d "dist/src" ]; then
              # src folder exists in dist, use the original path
              pm2 start dist/src/main.js --name $APP_NAME -i max
            else
              # No src folder, use the alternative path
              pm2 start dist/main.js --name $APP_NAME -i max
            fi
            pm2 save
          fi

          # Clean up working directory
          git reset --hard HEAD
