name: deploy-nest-starter-project

on:
  push:
    branches: ['main']

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          logout: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.REPO }}

  deploy:
    runs-on: Linux
    needs: build-and-push-docker-image
    environment: prod
    steps:
      - name: Stop and remove the running docker container
        run: docker stop ${{vars.PROJECT_NAME}} && docker rm ${{vars.PROJECT_NAME}} || true
      - name: Remove the old docker image
        run: docker rmi ${{vars.REPO}} || true
      - name: pull the latest image from DockerHUB
        run: docker pull ${{ vars.REPO }}
      - name: run the latest project container
        run: docker run -d -p 3000:3000 --restart unless-stopped --name ${{vars.PROJECT_NAME}} ${{ vars.REPO }}
